### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by fiburg** [fiburg/cmos_lex#1]
- [x] Liveplot contains three plots - sky image + sky image with masked cloud + shadow map
- [x] Read ceilometer data
- [x] Color of station in plot depends on cloud cover
- [x] Improve input data stream
- [x] cloud mask from original image, not from cropped one, cut sun
- [x] si index dependent on sun position (asca)
- [x] correct the azimuth of sky imagers
- [ ] correct the alignment of sky imagers
- [ ] read radiation data to validate
