### ISSUE TITLE
Todo Finn

### ISSUE THREAD

**Issue by fiburg** [fiburg/cmos_lex#3]
Vom Wolkenbild zur Verschattungskarte
- [x] Texte überlesen/überarbeiten
- [x] Schriftgrößen auf Plots vergrößern

Eine Verschattungskarte aus einem Wolkenkameranetzwerk
- [ ] Schriftgrößen auf Plots vergrößern
- [x] Pyranometerdaten einlesen
